# Generated by Django 5.0.2 on 2024-02-28 14:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(max_length=50)),
                ("interest_rate", models.FloatField(max_length=200)),
                (
                    "borrower_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(max_length=50)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "Loan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.loan"
                    ),
                ),
            ],
        ),
    ]
